### ISSUE TITLE
ssl on kovan.api needs cert

### ISSUE THREAD

**Issue by okwme** [GFJHogue/0xchange-server#2]

**Comment by GFJHogue** [comment]
@okwme 
```
Failed authorization procedure. kovan.api.0xchange.me (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Connection refused
```

**Comment by GFJHogue** [comment]
Let's Encrypt seemed to not be able to connect to different subdomains for unknown reasons. Ended up using `api.0xchange.me/kovan/`... for the testnet version. b9f7c75cf4adc96d2fe6acf3ca877d219f599033
